spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Passengers
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: Drivers
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: Rides
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka