server:
  port: 8082
spring:
  application:
    name: driver-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cab_aggregator
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/taxi-realm
          jwk-set-uri: http://localhost:8180/realms/taxi-realm/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
rating-service:
  exchange: driver-rating-exchange
  queue: driver-rating-queue
  routing-key: driver-rating
driver-service:
  ride:
    exchange: ride-driver-exchange
    queue: ride-driver-queue
  auth:
    exchange: auth-driver-exchange
    queue: auth-driver-queue
ride-service:
  exchange: driver-ride-exchange
  queue: driver-ride-queue
  routing-key: driver-ride
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  endpoint:
    health:
      show-details: always
feign-client:
  rating-service:
    name: rating-service
    path: /api/v1/ratings/drivers
  ride-service:
    name: ride-service
    path: /api/v1/rides
