scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8081',
                  'host.docker.internal:8082',
                  'host.docker.internal:8083',
                  'host.docker.internal:8084',
                  'host.docker.internal:8085',
                  'host.docker.internal:8086',]
